

export const AppointmentList = [
    {
        id: 1,
        name: 'Rashini Nethmini',
        contactNumber:'231444144',
        invoice: '2589721',
        product: 'Tablet',
        issue: 'The touchscreen of my tablet does not work',
        voiceSrc:'http://mp3.ananmanan.lk/sinhala_mp3/Arash_ft_Helena_Broken_Angel.mp3',
        isAccept:false,
    },
    {
        id: 2,
        name: 'Prasadi Sankalpana',
        contactNumber:'231444144',
        invoice: '2599720',
        product: 'Laptop',
        issue: 'My speaker gives a trembling sound',
        voiceSrc:'http://mp3.ananmanan.lk/sinhala_mp3/Arash_ft_Helena_Broken_Angel.mp3',
        isAccept:false,
    },
    {
        id: 3,
        name: 'Anudhi Disara',
        contactNumber:'231444144',
        invoice: '9309725',
        product: 'TV',
        issue: 'Display is not working',
        voiceSrc:'http://mp3.ananmanan.lk/sinhala_mp3/Arash_ft_Helena_Broken_Angel.mp3',
        isAccept:false,
    },
    {
        id: 4,
        name: 'Prasadi Sankalpana',
        contactNumber:'231444144',
        invoice: '2599720',
        product: 'Laptop',
        issue: 'Issue in speaker',
        voiceSrc:'http://mp3.ananmanan.lk/sinhala_mp3/Arash_ft_Helena_Broken_Angel.mp3',
        isAccept:false,
    },

    {
        id: 5,
        name: 'Prasadi Sankalpana',
        contactNumber:'231444144',
        invoice: '2599720',
        product: 'Laptop',
        issue: 'Issue in spekear',
        voiceSrc:'http://mp3.ananmanan.lk/sinhala_mp3/Arash_ft_Helena_Broken_Angel.mp3',
        isAccept:false,
    },
    {
        id:6,
        name: 'Prasadi Sankalpana',
        contactNumber:'231444144',
        invoice: '2599720',
        product: 'Laptop',
        issue: 'Issue in spekear',
        voiceSrc:'http://mp3.ananmanan.lk/sinhala_mp3/Arash_ft_Helena_Broken_Angel.mp3',
        isAccept:false,
    },

]
